score1 = float(input("Enter your Foundation English score: "))
score2 = float(input("Enter your General Business score: "))
score3 = float(input("Enter your Introduction to Computer Systems score: "))
score4 = float(input("Enter your Computer Programming score: "))

print("--- Your Score ---")
print("Foundation English :",score1)
print("General Business :",score2)
print("Introduction to Computer Systems :",score3)
print("Computer Programming :",score4)
